# Generated by Django 4.1 on 2022-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='service',
            name='feature1_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature1_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='feature1_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='feature2_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature2_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='feature2_title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='service',
            name='feature3_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='feature3_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='service',
            name='feature3_title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
