# Generated by Django 4.1.3 on 2023-01-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_remove_service_feature1_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='main_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='main_titel',
            new_name='title',
        ),
    ]
