# Generated by Django 4.1.3 on 2023-01-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_rename_main_description_service_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceoverview',
            name='title',
        ),
        migrations.AddField(
            model_name='service',
            name='overview_title',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
