# Generated by Django 4.1 on 2022-10-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_remove_service_image_service_feature1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='feature_summery1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='feature_summery2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='feature_summery3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='feature_summery4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
