# Generated by Django 4.1 on 2022-10-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_service_feature_summery1_service_feature_summery2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='feature_summery1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature_summery2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature_summery3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='feature_summery4',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
