# Generated by Django 4.1 on 2022-10-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_service_feature_summery1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='feature_summery_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
