# Generated by Django 4.1.3 on 2023-01-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_service_main_description_service_main_titel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='feature1_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature1_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature1_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature2_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature2_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature2_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature3_description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature3_image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature3_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature_summery1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature_summery2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature_summery3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature_summery4',
        ),
        migrations.RemoveField(
            model_name='service',
            name='feature_summery_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='id',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ServiceOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.CharField(max_length=512)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overviews', to='Services.service')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Services.service')),
            ],
        ),
    ]
